# Generated by Django 4.2.15 on 2024-08-23 23:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_path),
        ),
    ]
